# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xci
# IP: The module: 'rxfifo_ip_4Kx64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxfifo_ip_4Kx64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxfifo_ip_4Kx64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xci
# IP: The module: 'rxfifo_ip_4Kx64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxfifo_ip_4Kx64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/rxfifo_ip_4Kx64/rxfifo_ip_4Kx64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxfifo_ip_4Kx64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
