# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.cache/wt [current_project]
set_property parent.project_path C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
set_property verilog_define {USE_DDR3_FIFO=1 USE_XPHY=1 USE_PVTMON=1} [current_fileset]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/br_sfifo_ip_4x32_synth_1/br_sfifo_ip_4x32.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/br_sfifo_ip_4x32_synth_1/br_sfifo_ip_4x32.dcp]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/pktctrl_fifo_ip_synth_1/pktctrl_fifo_ip.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/pktctrl_fifo_ip_synth_1/pktctrl_fifo_ip.dcp]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/rxfifo_ip_4Kx64_synth_1/rxfifo_ip_4Kx64.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/rxfifo_ip_4Kx64_synth_1/rxfifo_ip_4Kx64.dcp]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/ipcs_fifo_ip_synth_1/ipcs_fifo_ip.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/ipcs_fifo_ip_synth_1/ipcs_fifo_ip.dcp]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/gigerx_bcnt_fifo_ip_256x16_synth_1/gigerx_bcnt_fifo_ip_256x16.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/gigerx_bcnt_fifo_ip_256x16_synth_1/gigerx_bcnt_fifo_ip_256x16.dcp]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/gigerx_fifo_ip_256x8_synth_1/gigerx_fifo_ip_256x8.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/gigerx_fifo_ip_256x8_synth_1/gigerx_fifo_ip_256x8.dcp]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/gigerx_fifo_ip_256x64_synth_1/gigerx_fifo_ip_256x64.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/gigerx_fifo_ip_256x64_synth_1/gigerx_fifo_ip_256x64.dcp]
add_files -quiet C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/txfifo_ip_1024x64_synth_1/txfifo_ip_1024x64.dcp
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.runs/txfifo_ip_1024x64_synth_1/txfifo_ip_1024x64.dcp]
read_ip C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci
set_property used_in_implementation false [get_files -all c:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xdc]
set_property is_locked true [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci]

read_verilog -library xil_defaultlib {
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/common/synchronizer_simple.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/network_path/network_path_shared.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC2_vc709_2015_4.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_SYNTH/LMAC_SYNTH.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LPBK_MODULE/LPBK_MODULE.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/tcore_fmac_core_LE2.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/crc32_d64.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/eth_crc32_gen.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/tx_encap.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/gige_crc32x64.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/crc32_d16s.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/bsh32_dn_88.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo512x64_2clk.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/bsh8_dn_64.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/gigerx_fifo256x64_2clk.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/crc32_d8s.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/LMAC_CORE_TOP.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/gige_tx_encap.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/byte_reordering.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/tx_1G_wrap.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/gige_tx_gmii.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/rx_5G.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/tx_mac10g_crc32x64.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/g2x_ctrl.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/gigerx_fifo256x8.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/rx_decap_LE2.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/tx_10G_wrap.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/txfifo_1024x64.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/gige_s2p.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/fmac_register_if_LE2.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/ctrl_2G_5G.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo4Kx64.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/tx_xgmii_LE2.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/br_sfifo4x32.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/crc32_d24s.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/fmac_fifo4Kx8.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/rx_xgmii_LE2.v
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/LMAC_RTL/LMAC_CORE_TOP/gigerx_bcnt_fifo256x16.v
}
read_vhdl -library xil_defaultlib {
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/pvtmon/kcpsm6.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/pvtmon/power_test_control.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/pvtmon/vc709_power_test.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/pvtmon/power_test_control_program.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/clock_control/clock_control.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/hdl/clock_control/clock_control_program.vhd
}
read_xdc C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/constraints/v7_LMAC2_xgemac_xphy.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/constraints/v7_LMAC2_xgemac_xphy.xdc]

read_xdc C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/constraints/v7_LMAC2_base.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/constraints/v7_LMAC2_base.xdc]

read_xdc C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/constraints/v7_LMAC2_bit_rev1_0.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4/hardware/sources/constraints/v7_LMAC2_bit_rev1_0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top LMAC2_vc709_2015_4 -part xc7vx690tffg1761-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef LMAC2_vc709_2015_4.dcp
catch { report_utilization -file LMAC2_vc709_2015_4_utilization_synth.rpt -pb LMAC2_vc709_2015_4_utilization_synth.pb }
