# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xci
# IP: The module: 'gigerx_fifo_ip_256x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xci
# IP: The module: 'gigerx_fifo_ip_256x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/SUNNY2/LMAC2-vc709-2015-4/hardware/vivado/runs/LMAC2_vc709_2015_4.srcs/sources_1/ip/gigerx_fifo_ip_256x64/gigerx_fifo_ip_256x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gigerx_fifo_ip_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
