#!/bin/sh
[ "$1" != "upgrade" ] || exit 0
set -e
	update-alternatives --remove  add-shell /usr/sbin/add-shell.debianutils
	update-alternatives --remove  installkernel /usr/sbin/installkernel.debianutils
	update-alternatives --remove  remove-shell /usr/sbin/remove-shell.debianutils
	update-alternatives --remove  savelog /usr/bin/savelog.debianutils
	update-alternatives --remove  tempfile /bin/tempfile.debianutils
	update-alternatives --remove  which /usr/bin/which.debianutils
