#!/bin/sh
[ "$1" != "upgrade" ] || exit 0
set -e
if true && type update-rc.d >/dev/null 2>/dev/null; then
	if [ -n "$D" ]; then
		OPT="-f -r $D"
	else
		OPT="-f"
	fi
	update-rc.d $OPT dropbear remove
fi
  if [ -f "/etc/dropbear/dropbear_rsa_host_key" ]; then
        rm /etc/dropbear/dropbear_rsa_host_key
  fi
  if [ -f "/etc/dropbear/dropbear_dss_host_key" ]; then
        rm /etc/dropbear/dropbear_dss_host_key
  fi
