#!/bin/sh
set -e
	if false; then
		if [ -n "$D" ]; then
			OPTS="--root=$D"
		fi
		for SERVICE in    banner   bootmisc   checkfs   checkroot   devpts   dmesg   hostname   mountall   mountnfs   populate-volatile   read-only-rootfs-hook   rmnologin   sysfs   urandom; do
			systemctl $OPTS mask $SERVICE.service
		done
	fi

    # Delete any old volatile cache script, as directories may have moved
    if [ -z "$D" ]; then
        rm -f "/etc/volatile.cache"
    fi
