#!/bin/sh
[ "$1" != "upgrade" ] || exit 0
set -e
	update-alternatives --remove  passwd /usr/bin/passwd.shadow
	update-alternatives --remove  chfn /usr/bin/chfn.shadow
	update-alternatives --remove  chsh /usr/bin/chsh.shadow
	update-alternatives --remove  chpasswd /usr/sbin/chpasswd.shadow
	update-alternatives --remove  vipw /sbin/vipw.shadow
	update-alternatives --remove  vigr /sbin/vigr.shadow
	update-alternatives --remove  nologin /sbin/nologin.shadow
