# Automatically generated by configure - do not modify
SRC_PATH=/home/lewiz/sambashare/Software_Driver/Co-Sim/qemu/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
