# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/vivado/runs/LMAC2_vc709_2015_4.cache/wt [current_project]
set_property parent.project_path C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/vivado/runs/LMAC2_vc709_2015_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
set_property verilog_define {USE_DDR3_FIFO=1 USE_XPHY=1 USE_PVTMON=1} [current_fileset]
read_verilog -library xil_defaultlib C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/hdl/LMAC2-vc709-2015-4.v
read_vhdl -library xil_defaultlib {
  C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/hdl/pvtmon/kcpsm6.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/hdl/pvtmon/power_test_control.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/hdl/pvtmon/power_test_control_program.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/hdl/clock_control/clock_control.vhd
  C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/hdl/clock_control/clock_control_program.vhd
}
read_xdc C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/constraints/v7_LMAC2_xgemac_xphy.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/constraints/v7_LMAC2_xgemac_xphy.xdc]

read_xdc C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/constraints/v7_LMAC2_base.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/constraints/v7_LMAC2_base.xdc]

read_xdc C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/constraints/v7_LMAC2_bit_rev1_0.xdc
set_property used_in_implementation false [get_files C:/SUNNY2/LMAC2-vc709-2015-4-gate_level/hardware/sources/constraints/v7_LMAC2_bit_rev1_0.xdc]

synth_design -top LMAC2_vc709_2015_4 -part xc7vx690tffg1761-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef LMAC2_vc709_2015_4.dcp
catch { report_utilization -file LMAC2_vc709_2015_4_utilization_synth.rpt -pb LMAC2_vc709_2015_4_utilization_synth.pb }
